// Generated by CoffeeScript 1.7.1
(function() {
  window.lib = {
    server: {
      map: {
        "gs01": "Perfect World",
        "is01": "City of Abominations",
        "is02": "Secret Passage",
        "is03": "Unknown",
        "is04": "Unknown",
        "is05": "Firecrag Grotto",
        "is06": "Den of Rabid Wolves",
        "is07": "Cave of the Vicious",
        "is08": "Hall of Deception",
        "is09": "Gate of Delirium",
        "is10": "Secret Frostcover Grounds",
        "is11": "Valley of Disaster",
        "is12": "Forest Ruins",
        "is13": "Cave of Sadistic Glee",
        "is14": "Wraithgate",
        "is15": "Hallucinatory Trench",
        "is16": "Eden",
        "is17": "Brimstone Pit",
        "is18": "Temple of the Dragon",
        "is19": "Nightscream Island",
        "is20": "Snake Isle",
        "is21": "Lothranis",
        "is22": "Momaganon",
        "is23": "Seat of Torment",
        "is24": "Abaddon",
        "is25": "Warsong City",
        "is26": "Palace of Nirvana",
        "is27": "Lunar Glade",
        "is28": "Valley of Reciprocity",
        "is29": "Frostcover City",
        "is30": "Unknown",
        "is31": "Twilight Temple",
        "is32": "Cube of Fate",
        "is33": "Chrono City",
        "is34": "Wedding Chapel",
        "is35": "Guild Base",
        "is37": "Morai",
        "is38": "Phoenix Valley",
        "is39": "Endless Universe",
        "is40": "Morai Pitty Menty",
        "is41": "Endless Universe Super Mode",
        "is43": "Black ice Castle",
        "is44": "Skenario Pengujian1",
        "is45": "Skenario Pengujian2",
        "is46": "Skenario Pengujian3",
        "is50": "Realm Of Reflection",
        "arena01": "Atrium of Blood",
        "arena02": "Lost City Arena",
        "arena03": "Plume City Arena",
        "arena04": "Archosaur Arena",
        "bg01": "Territory War T-3 PvP",
        "bg02": "Territory War T-3 PvE",
        "bg03": "Territory War T-2 PvP",
        "bg04": "Territory War T-2 PvE",
        "bg05": "Territory War T-1 PvP",
        "bg06": "Territory War T-1 PvE",
        "is75": "Leveling Island"
      }
    },
    char: {
      classes: ['Warrior', 'Mage', 'Psychic', 'WereFox', 'WereBeast', 'Assassin', 'Archer', 'Priest', 'Seeker', 'Mystic'],
      cultivations: ['Inchoation - Lv1', 'Autoscopy - Lv9', 'Transform - Lv19', 'Naissance - Lv29', 'Reborn - Lv39', 'Vigilance - Lv49', 'Doom - Lv59', 'Disengage - Lv69', 'Nirvana - Lv79', '[Holy]Prime Immortal - Lv89', '[Dark]Daimon Baersark - Lv89', '[Holy]Pure Immortal - Lv99', '[Dark]Daimon Saint - Lv99', '[Holy]Ether Immortal - Lv109', '[Dark]Daimon Elder - Lv109']
    }
  };

}).call(this);

//# sourceMappingURL=util.map
